language: r
cache: packages
pandoc_version: 1.19.2.1

env:
  global:
    - secure: kXSmGTcqyv3qKIRBIO20Dc8SMdT0Ls/bhBDcvNnP7OUftc+KREH+Ri1cfSgVQOahpxpi8xL/CW2bdGcdypAwcKjJm6jzOLGRN7U+mV3Iuelf4MaKTnveTbybu11kuf2R8msUpRS8COivwpM1Qch87TT/XyWWtUIM9yVIR8s47iJ0kVHbw/HZDJcYyoaAezNXZm6zQbOstSvARY0eqnvStvBehjMcSDKi6S0ukx+wU9NHG/m50u74r1YaKkFUj8nFj6wB9BukboEHRZ+tdVp+S4jzLcd3ZofSSyT+PDizHVaUF1qV+YNoqujywkh4Re057PrdLqDN9UVbgJWRe+e9oIjY3TZoxedI70Xb96T3L2l5DyecQNAGshQesn+/PDocx95d6gWT15LWarWrtLgRDGUjO220shU/CBZTP24SzdsQ/S26cr7MXkl4Df0x1gSLA4uRoCIPRRSIvAiNEoM1MJX8MVBY7+dM7OYk7KgWSXA11LE+mAAifl5U/LaDzx4hpyIEE2aBeLrlKvxeGMO5UHuONn3FJSGE4GsByCTDPrKidFSqzc3ZnIescMJcLT0d+hDbNQ3DFHBwJuz3F4ZTJfs6ojHLQCpNL+7rccDwBPxZ51ohHK5VObQ7DFKxV5oITa92jDIpIup9mV7qDJ0eEWI8jXA+V+eVC8gfi+SrMeA=


before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
